### PR TITLE
Archisinal ink!ubator Milestone 2 Delivery

### PR DESCRIPTION
**Pull request by Tom-STEM**

### CODE REVIEW

**Comment by sventime** [comment]
Hello @HCastano and fellow reviewers,

I wanted to share a few brief updates regarding testing:

 - The Archisinal marketplace is now operational on our staging environment: https://marketplace-app-client.vercel.app/
 - It's configured for Shibuya testnet
 - You can access and use the marketplace on your mobile device through the SubWallet browser.

For more information: [README.md](https://github.com/Archisinal/marketplace-app) and [TESTING.md](https://github.com/Archisinal/marketplace-app/blob/main/TESTING.md) documents.

Looking forward to your review and comments. 

CC: @Tom-STEM

**Review by HCastano — APPROVED** [review]
Great work guys!

I played around with this and managed to create a collection and mint an NFT successfully 💪

One comment, the indexer does seem to be a bit slow. It took a bit of time between when I created the collection/minted the NFT before it actually showed up in the explore tab.

But yeah, nice stuff and thanks for providing all these links and a step-by-step testing guide. Made the review process quite easy for me.

**Comment by sventime** [comment]
> Great work guys!
> 
> I played around with this and managed to create a collection and mint an NFT successfully 💪
> 
> One comment, the indexer does seem to be a bit slow. It took a bit of time between when I created the collection/minted the NFT before it actually showed up in the explore tab.
> 
> But yeah, nice stuff and thanks for providing all these links and a step-by-step testing guide. Make the review process quite easy for me.

Thank you for the prompt response and your approval 🙏

I agree with the indexing speed. The current slowdown is due to indexing events from finalized blocks. It would be more efficient to index non-finalized data (while restricting listing before finalization) and then update it upon finalization. This should improve UX.

**Review by o-tsaruk — APPROVED** [review]
Hi! 
Well-written testing guide =). One thing I found on the web app - after login, I need to tap this button again because it isn't re-rendering (state management issue).

connect-button

**Review by 0xMarkian — APPROVED** [review]

**Comment by TtomaS7** [comment]
Hey team!

Here's the form for payment details: https://forms.gle/BUCKfygkiEvpdYna6.
Once you've filled it out, please let me know and be sure to specify what it pertains to; you can include the link to this PR delivery! Further details can be provided under the section: "Please describe which Milestone you have completed and attach the link to the Milestone delivery."

Should you have any questions, don't hesitate to ask. Thank you so much!

Important Note: PLEASE VERIFY YOUR ADDRESS, WHERE YOU WILL RECEIVE THE FUNDS, BEFORE FILLING OUT THE FORM!
For guidance on how to set up identity, refer to [this guide](https://support.polkadot.network/support/solutions/articles/65000181981-how-to-set-and-clear-an-identity).

**Comment by sventime** [comment]
Hi @TtomaS7, @HCastano!

It seems there's an issue with the bounty payment. It included a fee to the ink!ubator address of 4452 DOT. After claiming, archisinal_io received only 715 DOT, which is ~14% of the expected amount.

Hope you can help resolve this issue. Thank you!

https://explorer.polkascan.io/polkadot/account/13UVJyLnbVp9RBZYFwHZ1tkZ8SwaFNzs1jtgXPqe87VCT17Z
image

**Comment by HCastano** [comment]
@sventime hmm okay I think there was a misunderstanding in where the child fee was coming from. I assumed it came from the parent bounty fee. 

We'll get you sorted, don't worry!

**Comment by HCastano** [comment]
I've submitted a transfer request from our Multisig. Waiting on the other curators to approve - I'd expect that to happen by tomorrow at the latest.

**Pull request merged**
