### PR TITLE
Create starlay_finance_milestone_2.md

### PR DESCRIPTION
**Pull request by Chidasan**

### CODE REVIEW

**Comment by HCastano** [comment]
Hey, we haven't had time to review this yet, but we'll try to soon 🙇

**Review by HCastano — CHANGES_REQUESTED** [review]
This milestone really misses the mark for me.

First, the `repay_all` and `redeem_all` functions are really just special cases of
`repay` and `redeem`, which were already implemented in Milestone 1. They were even
introduced to the codebase at the same time, so I don't see why they are considered as
being different.

The mobile support doesn't work, as seen in my screenshots below. I tried in both Chrome
and Firefox.

Screenshot 2023-10-08 at 10 54 12 AM

Screenshot 2023-10-08 at 10 53 21 AM

This milestone doesn't have any post-audit refinements, since there has been no audit yet
(to be fair, this was mentioned).

The Flashloan functionality seems okay on the surface, but the documentation around it is
lacking. It's all Solidity based, whereas I expect code and examples showing how to
interact with the ink! contracts. I also expect better explanations of what a flashloan
is, any considerations I need to keep in mind as a developer when using them, and
examples beyond pasting in a Starlay internal implementation.

There's also an issue around resources. In this milestone I only see code written by
Wolf. Where is the other FTE and the other 4 PTEs?

**Comment by Chidasan** [comment]
Hi @Hcastano

Thanks for your reply. 

 >First, the `repay_all` and `redeem_all` functions are really just special cases of `repay` and `redeem`, which were already implemented in Milestone 1. They were even introduced to the codebase at the same time, so I don't see why they are considered as being different.

When we submitted the ecosystem grant application over five months ago, we believed there was a need to differentiate between the functions. However, upon further evaluation and development, we've come to the conclusion that there isn't a necessity to separate them. We anticipate things to proceed as planned, but as with any development, there can be slight deviations or nuances that arise. We appreciate your understanding in this matter.

>The mobile support doesn't work, as seen in my screenshots below. I tried in both Chrome and Firefox.

My apologies for the oversight regarding the link. The development has indeed been completed. Please check the correct link here: https://starlay-ui-mirrored-inhouse-git-feature-mobile-neo-astar.vercel.app/. Additionally, we launched the mobile version yesterday, and the link provided initially will work as well.

>This milestone doesn't have any post-audit refinements, since there has been no audit yet (to be fair, this was mentioned).

While it's similar to repay_all and redeem_all case, it's important to note that when we drafted the ecosystem grant application over 5 months ago, our perspective and understanding were different. Even the scope for the audit was only finalized last week. While there are deviations from the initial plan, we intend to launch after the post-audit refinements are completed. 

>The Flashloan functionality seems okay on the surface, but the documentation around it is lacking. It's all Solidity based, whereas I expect code and examples showing how to interact with the ink! contracts. I also expect better explanations of what a flashloan is, any considerations I need to keep in mind as a developer when using them, and examples beyond pasting in a Starlay internal implementation.

We understand the need for more comprehensive documentation and examples for the Flashloan functionality. We are currently in the process of preparing a GitBook for Wasm, which will be available after the launch of Starlay on Wasm. In the meantime, you can refer here for more details: https://github.com/starlay-finance/starlay-protocol-wasm/tree/main#flashloan-implementation

>There's also an issue around resources. In this milestone I only see code written by Wolf. Where is the other FTE and the other 4 PTEs?

When we initially submitted the proposal over five months ago, we anticipated a completion timeline of two months. However, various unforeseen factors caused delays, leading us to our current timeline. 

While @wolfwarrier14 is our primary FTE working on the core functionalities, the project's scope and complexity required collaborative efforts:

- @qudacki handled the frontend.
- @un-ast was responsible for the review part, as seen in [[this pull request](https://github.com/starlay-finance/starlay-protocol-wasm/pull/140)](https://github.com/starlay-finance/starlay-protocol-wasm/pull/140).
- I have been managing communications and ensuring that all stakeholders are aligned.
- @artat9 engaged in detailed discussions with @wolfwarrier14, especially concerning Wasm.
- @zk-neo oversaw the entire project, including liaising with auditors.

It's evident that the combined efforts of our team go beyond the capacity of 1 FTE and 4 PTEs, especially considering the ongoing development for this grant program

**Comment by HCastano** [comment]
> When we submitted the ecosystem grant application over five months ago, we believed there was a need to differentiate between the functions. However, upon further evaluation and development, we've come to the conclusion that there isn't a necessity to separate them. We anticipate things to proceed as planned, but as with any development, there can be slight deviations or nuances that arise. We appreciate your understanding in this matter.
>
> ...
> 
> While it's similar to repay_all and redeem_all case, it's important to note that when we drafted the ecosystem grant application over 5 months ago, our perspective and understanding were different. Even the scope for the audit was only finalized last week. While there are deviations from the initial plan, we intend to launch after the post-audit refinements are completed.

I understand that you couldn't have known the full scope and implementation details ahead of time, but I don't think it's fair for us to pay for a new "feature" that's really an already implemented feature with a different argument.

Bottom line for me is that the scope of this milestone has changed in such a way that I
don't think the initially agreed value is acceptable.

We should split this milestone into two:

1. Flashloan functionality + mobile support
2. The post-audit refinement work


> My apologies for the oversight regarding the link. The development has indeed been completed. Please check the correct link here: https://starlay-ui-mirrored-inhouse-git-feature-mobile-neo-astar.vercel.app/. Additionally, we launched the mobile version yesterday, and the link provided initially will work as well.

When I was doing my initial review I didn't see any new contributions on the front-end repo since it looks like the mobile support was only merged into `main` last week. Thanks for updating the links and stuff though.

That said, it still looks like the mobile support doesn't work on the original link, or on the updated Vercel link.

image

image

> We understand the need for more comprehensive documentation and examples for the Flashloan functionality. We are currently in the process of preparing a GitBook for Wasm, which will be available after the launch of Starlay on Wasm. In the meantime, you can refer here for more details: https://github.com/starlay-finance/starlay-protocol-wasm/tree/main#flashloan-implementation

Can you add this link to the submission text?


> While @wolfwarrier14 is our primary FTE working on the core functionalities, the project's scope and complexity required collaborative efforts:
> 
> - @qudacki handled the frontend.
> - @un-ast was responsible for the review part, as seen in [this pull request](starlay-finance/starlay-protocol-wasm#140)
> 
> - I have been managing communications and ensuring that all stakeholders are aligned.
> - @artat9 engaged in detailed discussions with @wolfwarrier14, especially concerning Wasm.
> - @zk-neo oversaw the entire project, including liaising with auditors.


To be honest with you I'm skeptical with the scope of some of the team member contributions.

With @un-ast it looks like the only contribution they've had in the last few months isreviewing the one PR you linked.

image

Similarly with @artat9, I can't asses what "detailed discussions" are, especially if there's no evidence of them on GitHub.

image

**Comment by Chidasan** [comment]
@HCastano 

Thank you for your feedback. We understand your concerns and would like to clarify the following:

- As I said and you understand, the initial plan and the actual implementation may differ, but it's important to note that the milestone was approved based on the initial plan. Changing the milestone requirements after approval is not justified. You can refer to the approval here: https://github.com/use-inkubator/Ecosystem-Grants/pull/9
- The base development was focused on during the months of March and April, over a period of 8 weeks. You can verify the contributions of each team member by checking their respective repositories. In addition to the development work, team members have also significantly contributed to communications (via Slack) and design discussions (via Notion), ensuring that all aspects of the project are aligned and cohesive.
- Although not included in the grant, we have developed additional features such as support for Openbrush (which is no longer available), flashloan support, audit discussion, main functions improvements and so on.

Given the above points:

- Apologize for the mobile support. We have now addressed this and kindly ask you to verify.
- We will not be changing the milestone for the reasons mentioned above. There will always be discrepancies between the plan and the actual implementation. It is not fair to overturn the approval at this final stage, especially considering that it took over 1.5 months to get approved. Regardless, we plan to proceed with the post-audit refinements before launching.
- We have added the link (https://github.com/starlay-finance/starlay-protocol-wasm/tree/main#flashloan-implementation) to the submission text (in the additional information)

We hope this clarifies any concerns you may have, and we are open to further discussion if needed.

**Comment by HCastano** [comment]
> As I said and you understand, the initial plan and the actual implementation may differ, but it's important to note that the milestone was approved based on the initial plan. Changing the milestone requirements after approval is not justified. You can refer to the approval here: https://github.com/use-inkubator/Ecosystem-Grants/pull/9

I'm not suggesting to overturn the third milestone. A re-scoping would would work in your favour in this case.

The first part, flashloans and mobile support, could be approved and paid out essentially right away.

The second part, audit fixes, would need to wait until after the audit. This will probably be a month from now.

Otherwise the whole milestone will be held up until the audit fixes are implemented.

**Comment by HCastano** [comment]
> I apologize for the misunderstanding. I thought we needed to get approval from other reviewers to split the milestone. If we don't need approval from other reviewers, that would be great. Thank you for your suggestion. In this case, should I edit the title and content of the "Create starlay_finance_milestone_2" commit to 2-1, and then submit 2-2 after completing the 2-1?

Can you create a PR into the Ecosystem-Grants repo editing your application with the split we talked about here? It should be pretty easy to get that merged. Afterwards we can re-assess this submission based on the new milestone 2 (or 3 I guess?) criteria, which would be just the flashloan and mobile functionality.

Once the audit and fixes are completed you can open another milestone PR for that.

> I don't understand why you think that way. From my perspective, we developed during March and April for 8 weeks, as initially planned periods (https://github.com/use-inkubator/Ecosystem-Grants/blob/master/applications/starlay_finance.md). From May to the present, we have been improving the code, adapting to Openbrush as requested, addressing audit issues, and developing features outside of the grant like the followings:

Yeah sorry, I'm a little on edge given some things that have happened with other submissions. So sorry if I've come across a bit crass.

**Comment by Chidasan** [comment]
@HCastano 

Apologize for the delayed response; I've been taking some time off due to my move to India.

No problem at all, I understand the pressure that comes with managing grant submissions and ensuring everything is on track. I appreciate your patience and guidance through this process.

I've updated the starlay_finance.md file in the Ecosystem Grants repository (https://github.com/Chidasan/Ecosystem-Grants/blob/master/applications/starlay_finance.md) to reflect our discussion about splitting the milestones. Here's the PR for the updated application: https://github.com/use-inkubator/Ecosystem-Grants/pull/35. 

Thank you for your understanding and for facilitating this process

**Comment by Chidasan** [comment]
@HCastano 
Following the approval of the ecosystem grants, we have made the changes discussed above. Please approve the modifications at your earliest convenience.
https://github.com/use-inkubator/Ecosystem-Grants/pull/35#event-10940874824

**Review by HCastano — APPROVED** [review]
LGTM, thanks!

**Review by h4x3rotab — APPROVED** [review]
LGTM. High quality UI and documentation. Very impressive.

**Review by DoubleOTheven — APPROVED** [review]

**Comment by TtomaS7** [comment]
Hey team!

Here's the form for payment details: https://forms.gle/BUCKfygkiEvpdYna6.
Once you've filled it out, please let me know and be sure to specify what it pertains to; you can include the link to this PR delivery! Further details can be provided under the section: "Please describe which Milestone you have completed and attach the link to the Milestone delivery."

Should you have any questions, don't hesitate to ask. Thank you so much!

Important Note: PLEASE VERIFY YOUR ADDRESS, WHERE YOU WILL RECEIVE THE FUNDS, BEFORE FILLING OUT THE FORM!
For guidance on how to set up identity, refer to [this guide](https://support.polkadot.network/support/solutions/articles/65000181981-how-to-set-and-clear-an-identity).

**Comment by Chidasan** [comment]
Hi @TtomaS7,
I have submitted our payment details now. Please confirm when you can.

**Comment by TtomaS7** [comment]
The payment is sent!
You can claim it in 4 days.
https://polkadot.subsquare.io/treasury/child-bounties/19_499

**Pull request merged**
