### PR TITLE
Decentralized Oracles - Milestone 1 - VRF

### PR DESCRIPTION
**Pull request by GuiGou12358**

### CODE REVIEW

**Comment by h4x3rotab** [comment]
Excellent. The demo works like a charm. Just need to get some Shibuya testnet token before requesting:

image

**Comment by h4x3rotab** [comment]
I've reviewed:

- The demo: Works very smoothly! Nice job.
- The Phat Contract (offchain program) oracle implementation:
    - Solid implementation. Actually the Phala team has already given a round of review before, and the necessary fixes were already applied
    - The random numbers are generated within the secure offchain workers' hardware RNG (backed by Intel SGX), and signed off by the worker's private key (thus verifiable). However, to make it further verifiable, you can consider to derive the randomness from the cryptographical KDF (key derivation function) provided by Phat Contract with a given salt. In this way, you can not only verify the correctness, but also reproduce any randomness and check it afterwards. This brings the verifiability to the next level.
    - Sample implementation (for EVM, just as a reference): https://github.com/Leechael/vrf-phat-contract
- The Consumer contract (on-chain) implementation:
    - The error handling can be improved, since now it doesn't report the exact error message, but it's already a very solid showcase of the oracle implementation, and how it's used in a typical ink contract.
    - I didn't find any security concerns, but since it uses OpenBrush extensively, I suggest @0xMarkian to give it another review.

Overall all the open source projects have very clear readme file and code style. From the technical perspective, I'm ok to merge this PR.

**Review by h4x3rotab — APPROVED** [review]

**Review by DoubleOTheven — APPROVED** [review]

**Comment by TtomaS7** [comment]
Hey team!

Here's the form for payment details: https://forms.gle/BUCKfygkiEvpdYna6.
Once you've filled it out, please let me know and be sure to specify what it pertains to; you can include the link to this PR delivery! Further details can be provided under the section: "Please describe which Milestone you have completed and attach the link to the Milestone delivery."

Should you have any questions, don't hesitate to ask. Thank you so much!

Important Note: PLEASE VERIFY YOUR ADDRESS, WHERE YOU WILL RECEIVE THE FUNDS, BEFORE FILLING OUT THE FORM!
For guidance on how to set up identity, refer to [this guide](https://support.polkadot.network/support/solutions/articles/65000181981-how-to-set-and-clear-an-identity).

**Comment by GuiGou12358** [comment]
Many thanks!
We just submitted the form for payment details.

**Comment by TtomaS7** [comment]
@GuiGou12358 Is it your address?
Please confirm, because it is verified with another name (not ink! Oracle)
https://polkadot.subscan.io/account/14ogWEsaFHYk1rDcRMLVApekUd3np4e1ker81tBF6odd39Q9

**Comment by GuiGou12358** [comment]
Yes, it is the correct address. Decentralized Oracles are built by the same team as Lucky dApp: 
https://portal.astar.network/astar/dapp-staking/dapp?dapp=zsv1gvepvmwfdshmwgczs4zyvmmwesbjwqjn4wdpuefrrpy

**Comment by TtomaS7** [comment]
The payment is sent!
You can claim it in 7 days. 
https://polkadot.subsquare.io/treasury/child-bounties/19_498

**Pull request merged**
