### PR TITLE
Added Band Deliverables

### PR DESCRIPTION
**Pull request by BEN-KULL**

### CODE REVIEW

**Review by o-tsaruk — COMMENTED** [review]
Hey! Testing guidelines are well described, but can you please move/add examples of usage or API calls to the Testing guidelines page? Along with that, it would be great if you provide some information about architecture overview or individual component details! 

By the way, is the article published somewhere? =)

**Comment by BEN-KULL** [comment]
> Hey! Testing guidelines are well described, but can you please move/add examples of usage or API calls to the Testing guidelines page? Along with that, it would be great if you provide some information about architecture overview or individual component details!
> 
> By the way, is the article published somewhere? =)

Hello, we have added examples of usage to the Testing Guildelines, we have also added an architecture overview to the Article. Said Article is unpublished at the moment, however we can post it to our blog website / twitter ( whichever is appropriate ) once the Grant has been completed. Thanks

**Review by o-tsaruk — APPROVED** [review]

**Comment by o-tsaruk** [comment]
@BEN-KULL thank you. I see you [noted](https://github.com/use-inkubator/Ecosystem-Grants/blob/master/applications/band-grants.md) that the article will be published. So, please, don't forget to do that.
Everything else looks OK for me =)

**Review by 0xMarkian — APPROVED** [review]

**Review by h4x3rotab — APPROVED** [review]
lgtm

**Comment by TtomaS7** [comment]
Hey team!

Here's the form for payment details: https://forms.gle/BUCKfygkiEvpdYna6.
Once you've filled it out, please let me know and be sure to specify what it pertains to; you can include the link to this PR delivery! Further details can be provided under the section: "Please describe which Milestone you have completed and attach the link to the Milestone delivery."

Should you have any questions, don't hesitate to ask. Thank you so much!

Important Note: PLEASE VERIFY YOUR ADDRESS, WHERE YOU WILL RECEIVE THE FUNDS, BEFORE FILLING OUT THE FORM!
For guidance on how to set up identity, refer to [this guide](https://support.polkadot.network/support/solutions/articles/65000181981-how-to-set-and-clear-an-identity).

**Pull request merged**
