### PR TITLE
Bright Disputes - Milestone 3

### PR DESCRIPTION
**Pull request by bufta**
Delivery document for Bright Disputes - Milestone 3

### CODE REVIEW

**Review by HCastano — COMMENTED** [review]
Thanks for the submission! I've got a few questions/comments.

- To confirm, the changes for this milestone are contained in these commits?
    - https://github.com/bright/bright-disputes/commit/c8587f2e9c9da1235dc09c7204e1ff2049db766c
    - https://github.com/bright/bright-disputes/commit/ef0f6712f0f0551b68a11db52131af3670af3cea
    - https://github.com/bright/bright-disputes/commit/203b4d68c3b5bd2f5358f6734b0540377dfbb9a0
    - It's easier for me to consider a diff here than the full scope of work
- Your CI is currently not passing. Would you be able to fix that?
- Your Docker file doesn't build for me locally
    - First I had to add `--platform linux/amd64` (I'm on an `MX` Mac if that helps at all)
    - And then the next error I get while it tries to build the contracts:
        - `ERROR: Error invoking cargo metadata for Cargo.toml` 
        - `cargo metadata exited with an error: error: failed to get baby-liminal-extension as a dependency of package bright_disputes v0.1.0 (/bright_dispute/contract)`
- Are Docker images being published to Docker Hub?
- Have you been able to upstream any changes into Aleph Zero, or is a fork of their node still a hard requirement here?
- Do you mind making a short video (E.g a 1-2 min Loom video) showing the functionality added as part of this milestone?
    - Doesn't need to be anything fancy, contract deployment + interaction via the CLI is all I'm looking for 
    - This would make it easier to assess the milestone

**Comment by mgralinski-bright** [comment]
1. Yes, those are the changes for this milestone as well as [Improve bright disputes](https://github.com/bright/aleph-node/commit/302fb9c63a51646c0ad708dabbf61bb300e4e7a2) from the aleph-node fork.
2. Is fixed now. We had some issue with the Github CI credentials.
3. We recommend to build and test on the Intel chipsets.
4. `error: failed to get baby-liminal-extension as a dep..`, did you run `git submodule update --init --recursive`?
5. We have published docker images for our script, to build and deploy smart contract on the aleph-node:
* [aleph-node](https://hub.docker.com/r/brightinventions/disputes-node)
* [ink-environment](https://hub.docker.com/r/brightinventions/disputes-ink-dev)
* [cliain](https://hub.docker.com/r/brightinventions/disputes-cliain)
6. We needed to create a fork for the aleph-node repository, mainly for the extension of the `liminal-ark-relations` library, where we needed to define our custom ZKP relations.
7. Sure we can provide a short video, to show the functionality of the CLI and Bright Disputes, but form what we already see the best user experience will be after the 4-th milestone where we implement UI.

**Comment by HCastano** [comment]
> We recommend to build and test on the Intel chipsets.

Given that the M-series Macs have been out for like three years now, I don't think that's a good enough answer 😄

If you run your builds with something like `--platform=linux/amd64,linux/arm64` you can get support for both.

> did you run git submodule update --init --recursive

I did not, I expect the Docker build process to take care of everything for me. If you have published node images you might be able to leverage those in this Dockerfile.

> We have published docker images for our script, to build and deploy smart contract on the aleph-node:

Cool! They're pretty old though, do you mind updating them with the changes from the latest milestone? You may want to [consider automating this step](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images) if you haven't already.

> Sure we can provide a short video, to show the functionality of the CLI and Bright Disputes, but form what we already see the best user experience will be after the 4-th milestone where we implement UI.

I'm not interested that much in the user experience (in this milestone). I just want to quickly see the functionality demo'd.

**Comment by mgralinski-bright** [comment]
Hello @HCastano ,

We will be grateful if you would like to check our delivery again. We made a small commit, with a few changes:
* added demo movie of the showcase, which is stored in our repository ([showcase_cli.mov](https://github.com/bright/bright-disputes/blob/main/doc/showcase_cli.mov))
* we provided docker images for the ARM64 on the docker hub, and create a small [script](https://github.com/bright/bright-disputes/blob/main/scripts/cli.sh) to run commands. Thanks to this, you will be able to run [deploy.sh](https://github.com/bright/bright-disputes/blob/main/scripts/deploy.sh) script on your Mac MX.

**Review by HCastano — APPROVED** [review]
I tried running things locally with the Docker image and everything seemed to go alright,
so good work.

The video was useful as well, so thanks for that. I would like to see the video posted
somewhere more visible though - having to download it to view it was pretty annoying.

Feedback about your Docker setup:
- I still needed to pull the node submodule before things ran succesfully, this should be
  abstracted away if I'm using Docker
- The published images for `disputes-ink-dev` and `disputes-node` are ~2GB and ~4GB in
  size respectively
    - When uncompressed locally they're ~7GB and ~15GB respectively!
    - This is unacceptable from a DevEx or DevOps point of view
    - Please look into using multi-stage Docker builds to bring down the size for this
        - https://docs.docker.com/build/building/multi-stage/
        - https://blog.alexellis.io/mutli-stage-docker-builds/
        - https://github.com/paritytech/polkadot-sdk/blob/53f615de503c8936c2639f51b99019c64eab1018/substrate/docker/substrate_builder.Dockerfile#L18
    - This is useful even for selfish reasons, like saving costs on CI minutes and
      bandwith if you use them for deployments, testing, etc.

Since the functionality is there, you don't *need* to fix the Docker stuff, but I'd say
it's in your best interest to do so.

I would also update your intruction docs to be more generic across things like addresses.
E.g, using `$CONTRACT_ADDRESS` instead of `5ABC...`. This will make it clear to readers
what they need to update for their own setups.

**Comment by bufta** [comment]
Hi @TtomaS7 @h4x3rotab, hope all is well on your side. Do you know when we could expect the second review? Our next milestone is ready for some time and we'd love to follow with the next delivery. We'd greatly appreciate any feedback from your side.

**Review by DoubleOTheven — APPROVED** [review]
Hey guys, nice work. Apologies for the delay on the second review.

I agree that multistage Docker builds would be a nice improvement, but definitely not required.

**Comment by TtomaS7** [comment]
Hey team!

Here's the form for payment details: https://forms.gle/BUCKfygkiEvpdYna6.
Once you've filled it out, please let me know and be sure to specify what it pertains to; you can include the link to this PR delivery! Further details can be provided under the section: "Please describe which Milestone you have completed and attach the link to the Milestone delivery."

Should you have any questions, don't hesitate to ask. Thank you so much!

Important Note: PLEASE VERIFY YOUR ADDRESS, WHERE YOU WILL RECEIVE THE FUNDS, BEFORE FILLING OUT THE FORM!
For guidance on how to set up identity, refer to [this guide](https://support.polkadot.network/support/solutions/articles/65000181981-how-to-set-and-clear-an-identity).

**Comment by bufta** [comment]
Hi @TtomaS7, I would just like to check in to ask if you know when we can expect finalisation of this milestone & token transfer? Also, we've already followed with [a PR for our next milestone](https://github.com/use-inkubator/Grant-Milestone-Delivery/pull/18). We would greatly appreciate it if we could receive some update :)

**Comment by TtomaS7** [comment]
we will initiate the payment shortly!

**Comment by bufta** [comment]
Hi @TtomaS7, when do you think we could expect the payment? :)

**Pull request merged**
