### PR TITLE
Ink! Contract Multisig - Milestone 2 Delivery

### PR DESCRIPTION
**Pull request by DiegoTorresborda**
Last Milestone Delivery for [Ink! Contract Multi sig](https://github.com/use-inkubator/Ecosystem-Grants/blob/master/applications/ink_contract_multi-sig.md)

### CODE REVIEW

**Review by HCastano — COMMENTED** [review]
I'm impressed with what I've seen so far, great work guys!

I set up a multisig and used it to call a contract as well as play around with changing
settings on a live multisig. Everything worked as expected 💪

I will say though, the information provided to signers could be improved.

When I was proposing a call to a smart contract I was asked to upload an ABI. When I was
reviewing this transaction for an approval there was nothing in the UI to indicate what I
was about to sign, beyond the contract address and method selector. There was no option
for me to upload an ABI file either.

Screenshot 2024-01-25 at 7 57 26 PM

Similarly, when reviewing a transaction that changed the settings of my multisig there
was no indication what the setting change was going to be. I had to dig into the
"Advanced Details" tab to see what was going to happen. 

Screenshot 2024-01-25 at 8 06 09 PM


Especially for the multisig setting changes this information should be very clearly shown
to users without the need to dig into an "Advanced Details" section. These are standard
details needed in order to safely sign a transaction.

I wonder if you can (in the future) add integration with [ChainIDE and Polkaholic's](https://github.com/use-inkubator/Grant-Milestone-Delivery/pull/8) tooling
which can provide more info around "verified" contracts.

When I added my addresses to the "Address Book" I thought they names I assigned to each
address would show up in the transaction confirmation page. This was not the case. I
thought maybe it was an SS58 issue (Substrate vs. Shibuya addresses) so I tired adding
both variants to the address book and they still didn't show up.

It would also be nice to have the multisig name show up instead of just the multisig
address. I might be managing many multisig from the same account and I want to be sure
that I'm approving for the correct one.

After approving a transaction I get dropped into the "Queue" tab. I'd like to keep the
modal showing me the approved transaction open - or at least get dropped into the
"History" tab to see what I just signed. I can see a workflow where maybe you have a lot
of transactions to approve and staying in the "Queue" tab is better. In that case keeping
the approved transaction modal open would be the way to go.

After proposing a transaction I wasn't allowed to "Reject" it. Maybe I proposed a
transaction with an incorrect transfer value and want to cancel it (or at least vote to
cancel, since I'd still need the other signers to reject as well). I'm not entirely sure
if this is a UI limitation, or if the underlying smart contract logic would have to
change here.

Last thing, I promise! The ["Transaction builder" docs](https://docs.xsigners.io/docs/use_tx_builder) don't have any screenshots 😉

**Comment by 0xLucca** [comment]
@HCastano  Thank you, we really appreciate the encouraging words!

> I will say though, the information provided to signers could be improved.

We have made improvements here by updating the transaction details shown to signers. 

There is no longer a need to click into an "Advanced Details" section to view this information. Now it allows users to more safely and easily review transactions before approving. 

> When I was proposing a call to a smart contract I was asked to upload an ABI. When I was reviewing this transaction for an approval there was nothing in the UI to indicate what I was about to sign, beyond the contract address and method selector. There was no option for me to upload an ABI file either.

This is not the expected behavior - thanks to your comment we found an issue with the production server configuration. 

Now if you create a new transaction, you should see the relevant transaction details including the method name, argument names, and values.

The information for decoding the raw data is currently stored in a centralized database in order to present it to users. When you propose a transaction, this information is sent to our db and then it is retrieved when shown to users.
In the future, we expect to allow users to upload the ABI as well, to enable decentralized decoding of the raw transaction data.

> I wonder if you can (in the future) add integration with https://github.com/use-inkubator/Grant-Milestone-Delivery/pull/8 tooling which can provide more info around "verified" contracts.

This seems like an incredible add-on that would fit great with our intended changes. 

In the future, the transaction data could be retrieved not only from our centralized service, but also from the trusted ABI obtained from what you are recommending, or it could come from an ABI provided by the user directly in the frontend.

> When I added my addresses to the "Address Book" I thought they names I assigned to each
address would show up in the transaction confirmation page. This was not the case. I
thought maybe it was an SS58 issue (Substrate vs. Shibuya addresses) so I tired adding
both variants to the address book and they still didn't show up.

We have now addressed this, and the address book names should show up as expected in the transaction confirmation screens. 

The addresses involved in a transaction are now replaced by their address book names and truncated addresses, if they are in the user's address book or are part of the set of signers for that multisig. 

It also now indicates clearly when an address corresponds to the currently connected account.

> It would also be nice to have the multisig name show up instead of just the multisig
address. I might be managing many multisig from the same account and I want to be sure
that I'm approving for the correct one.

I'm not entirely sure if I fully understand your concern there. But to clarify - in the transaction approval screens, the multisig name and identifier address are both shown in the top left corner. Additionally, now if the multisig address is part of a transaction, the multisig's name is also clearly displayed in the transaction details content now.

> After approving a transaction I get dropped into the "Queue" tab. I'd like to keep the
modal showing me the approved transaction open - or at least get dropped into the
"History" tab to see what I just signed. I can see a workflow where maybe you have a lot
of transactions to approve and staying in the "Queue" tab is better. In that case keeping
the approved transaction modal open would be the way to go.

We now display an additional modal when a transaction reaches its approval threshold and is executed (or conversely gets cancelled if the rejections make it impossible to reach the threshold).

Specifically, this new modal shows the user the transaction ID that was just executed/cancelled. It also provides two options:

- Stay on the Queue tab to keep processing additional pending transactions
- Redirect to the History tab to view details of the transaction that was just resolved

> After proposing a transaction I wasn't allowed to "Reject" it. Maybe I proposed a
transaction with an incorrect transfer value and want to cancel it (or at least vote to
cancel, since I'd still need the other signers to reject as well). I'm not entirely sure
if this is a UI limitation, or if the underlying smart contract logic would have to
change here.

This is intended behavior - when someone proposes a transaction, it is assumed they are in favor of executing it, so it gets automatically approved in the contract. That's why the proposer cannot reject it afterwards.

We see this as a nice feature to streamline transaction creation and approval. However, you raise a good use case for being able to change your mind and cancel a transaction you have proposed.

This could be improved in the future to allow participants who have already voted positively or negatively to flip their vote in the other direction.

> Last thing, I promise! The ["Transaction builder" docs](https://docs.xsigners.io/docs/use_tx_builder) don't have any screenshots 😉

Ups, we missed that one! Thanks for catching that oversight. The docs have now been updated to include the screenshots.


We appreciate you taking the time to thoroughly review the project. Thanks again for the feedback!

**Review by HCastano — APPROVED** [review]
Tested everything again, and things mostly look good. I ran into a couple of hiccups, but
I don't think they're big enough to warrant another full review. So good job!

> We have now addressed this, and the address book names should show up as expected in the transaction confirmation screens.

I still found a place in the UI where this wasn't reflected. It was when I was trying to
update the multisig settings.

Screenshot 2024-02-11 at 10 16 08 AM

> We now display an additional modal when a transaction reaches its approval threshold and is executed (or conversely gets cancelled if the rejections make it impossible to reach the threshold).
>
> Specifically, this new modal shows the user the transaction ID that was just executed/cancelled. It also provides two options:
>
> Stay on the Queue tab to keep processing additional pending transactions
> Redirect to the History tab to view details of the transaction that was just resolved

So this ended up getting stuck for me after I submitted a contract transaction.

https://github.com/use-inkubator/Grant-Milestone-Delivery/assets/12344623/f177b7e7-dfe2-47d0-9d6a-347e719fa9fd


It did work as expected after updating my multisig settings.

**Comment by 0xLucca** [comment]
Hey @HCastano! Hope you are doing well.

> Tested everything again, and things mostly look good. I ran into a couple of hiccups, but
I don't think they're big enough to warrant another full review. So good job!

Thanks for the review and additional testing. I'm glad to hear things are looking good overall. We will take a look at those couple of minor hiccups you mentioned.

> I still found a place in the UI where this wasn't reflected. It was when I was trying to
update the multisig settings.

Regarding the inconsistency you found in the UI when trying to update the multisig settings - this happens because the signers information and the address book are stored separately, so for now the signers information takes precedence. We can look into better syncing these up.

> So this ended up getting stuck for me after I submitted a contract transaction.

Sorry to hear the modal got stuck for you after submitting a contract transaction. We will investigate this and fix it.

Lastly, please let us know if there is anything further you need from our side before considering this ready for final review. Should we go ahead and ping Sam to get his input? We're ready to address any other issues he might find as well. Just let us know the next steps.

**Comment by TtomaS7** [comment]
Hey team!

Here's the form for payment details: https://forms.gle/BUCKfygkiEvpdYna6.
Once you've filled it out, please let me know and be sure to specify what it pertains to; you can include the link to this PR delivery! Further details can be provided under the section: "Please describe which Milestone you have completed and attach the link to the Milestone delivery."

Should you have any questions, don't hesitate to ask. Thank you so much!

Important Note: PLEASE VERIFY YOUR ADDRESS, WHERE YOU WILL RECEIVE THE FUNDS, BEFORE FILLING OUT THE FORM!
For guidance on how to set up identity, refer to [this guide](https://support.polkadot.network/support/solutions/articles/65000181981-how-to-set-and-clear-an-identity).

**Pull request merged**
